name: coopandreas_launcher
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  window_manager: ^0.4.2
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.1.11
  animations: ^2.0.11
  buttons_tabbar: ^1.3.13
  dropdown_button2: ^2.3.9
  intl: ^0.19.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  flutter_animated_button: ^2.0.3
  ffi: ^2.1.2
  win32: ^5.5.1
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true